// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt-EyRge_tPnZJXFwfUUMbDYlFiXP_PYA',
    appId: '1:304348631944:web:7346ae61e3422b403da03d',
    messagingSenderId: '304348631944',
    projectId: 'ptoventa-c9da9',
    authDomain: 'ptoventa-c9da9.firebaseapp.com',
    storageBucket: 'ptoventa-c9da9.appspot.com',
    measurementId: 'G-6TR4SWJR15',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWFml2s3eoyl-PUv5rlPdYmJVkwAC5Ti8',
    appId: '1:304348631944:android:cf0b99a35a0e0d2c3da03d',
    messagingSenderId: '304348631944',
    projectId: 'ptoventa-c9da9',
    storageBucket: 'ptoventa-c9da9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0aiPTIgwADehx-zJ5JFHFPvsEKNsjm0w',
    appId: '1:304348631944:ios:31b741b9434fd6513da03d',
    messagingSenderId: '304348631944',
    projectId: 'ptoventa-c9da9',
    storageBucket: 'ptoventa-c9da9.appspot.com',
    iosClientId: '304348631944-ubnh101o85989c26uu608bkb7rbjve0o.apps.googleusercontent.com',
    iosBundleId: 'com.example.ptovent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0aiPTIgwADehx-zJ5JFHFPvsEKNsjm0w',
    appId: '1:304348631944:ios:31b741b9434fd6513da03d',
    messagingSenderId: '304348631944',
    projectId: 'ptoventa-c9da9',
    storageBucket: 'ptoventa-c9da9.appspot.com',
    iosClientId: '304348631944-ubnh101o85989c26uu608bkb7rbjve0o.apps.googleusercontent.com',
    iosBundleId: 'com.example.ptovent',
  );
}
